# pylint: skip-file

""""
Title: Utils.py
Author: Han Tong
Date: 2023-12-29
Python Version: Python 3.11.3
Description: All useful functions we use
"""

import logging
import re
from collections import OrderedDict
from itertools import islice
from config import get_config
from scipy.stats import spearmanr
import os
import numpy as np
import pandas as pd
import torch
import csv
import warnings
from scipy.linalg import svd
import torch.nn.functional as F
warnings.filterwarnings("ignore")
import time
config = get_config()

def get_values(data):
    if isinstance(data, pd.DataFrame) or isinstance(data, pd.Series):
        return data.values
    return data


def grep_index(pattern, name_all):
    """
    find pattern in name_all
    name_all can be a string or strings
    """
    if isinstance(name_all, str):
        return [0] if re.match(pattern, name_all) else []
    else:
        return np.where([re.match(pattern, name) for name in name_all])[0]

def grepl(pattern, name_all):
    """
    whether can we find pattern in name_all or not
    name_all is a string
    """
    return bool(re.match(pattern, name_all))


def id_map(codes, name_all, shift=0, concat=True):
    """
    return the location of codes in name_all
    add shift alternatively
    """
    result = [np.where(name_all == name)[0] for name in codes]
    if not result:
        return np.array([])
    else:
        if concat:
            return np.concatenate(result) + shift
        else:
            return result

    

def unique_slice(s, num_codes=20):
    """
    return the first num_codes unique codes
    """
    return list(islice(OrderedDict.fromkeys(s), num_codes))
    

def ret_type(codes, sep = ":"):
    """
    codes should be a list []
    """
    codes_split = [code.split(sep)[0] for code in codes]
    return(codes_split)


def find_one_one(code, now_index, name_all):
    """
    help codes find the index of one-one mapping codes across institutions except for leaf LOINC codes
    """
    return np.setdiff1d(id_map([code], name_all), now_index)


def find_other_local(name, P_OTOL, name_all):
    """
    help other lab and local lab to find their corresponding LOINCs generated by asking GPT4 again
    """
    ans = np.array(P_OTOL.iloc[id_map([name], P_OTOL.iloc[:, 0].values), 1 + np.where(~P_OTOL.iloc[id_map([name], P_OTOL.iloc[:, 0].values), 1:].isnull())[1]]).ravel()
    ind = id_map(ans, name_all)
    return ind
    

def find_same_par_gra(hie_loinc_rxn_phe, name_all, name_id, PARENT=1):
    """
    help LOINC, RXNORM, PheCode find their siblings
    hie_loinc_rxn_phe has 3 cols. self, parent, grandpa
    if PARENT = 1, find siblings; is PARENT = 2, find  cousins and siblings
    """

    name = name_all[name_id]
    parent_values = hie_loinc_rxn_phe.iloc[:, PARENT].values

    name_map = id_map([name], hie_loinc_rxn_phe.iloc[:, 0])
    
    if not name_map.any():
        return []

    now_id = name_map[0]
    sib_me_id_in_hie = np.where(parent_values == parent_values[now_id])[0]
    
    sib_id_in_hie = list(set(sib_me_id_in_hie) - {now_id})
    sib_names = hie_loinc_rxn_phe.iloc[sib_id_in_hie, 0].values
    
    sib_id_in_name = id_map(sib_names, name_all)
   
    return list(set(sib_id_in_name))

    
    
def sample(codes, max_len = 10):
    """
    sample max_len codes from codes
    """
    if len(codes) < max_len:
        return codes
    else:
        if isinstance(codes, np.ndarray):
            codes = codes.tolist()
        elif isinstance(codes, (set, dict)):
            codes = sorted(codes)
        return codes
    

def sample_cols(data, p):
    """
    sample p fraction columns from data
    """
    num_columns = data.shape[1]
    sampled_columns = np.random.choice(num_columns, int(p * num_columns), replace=False)
    sampled_data = data[:, sampled_columns]
    return sampled_data
    
    
def nega_sample(set1, set2, max_len = 10, DIFF=True):
    """
    Negative sampling function, you can negative sample set1 from set2\set1(if DIFF)
    """
    num_samples = len(set1)
    if DIFF:
        sample_range = set2 - set1
    else:
        sample_range = set2
    return set(np.random.choice(list(sample_range), min(num_samples, len(sample_range), max_len), replace=False))
    
    
def find_rel(name_id, REL_pairs, name_all):
    """
    find related pairs of code in REL_pairs table
    """
    REL_pairs.index = range(REL_pairs.shape[0])
    name = name_all[name_id]
    uni_rel = np.unique(np.union1d(REL_pairs["code2"][id_map([name], REL_pairs["code1"])], REL_pairs["code1"][id_map([name], REL_pairs["code2"])]))
    if len(uni_rel) == 0:
        return set()
    index_now = id_map(uni_rel, name_all)
    return index_now
    

def find_same_type(name_id, name_all):
    """
    find codes from same type
    """
    name = name_all[name_id]
    type_now = np.array(ret_type([name])[0])  # Extract only the first element of the inner list
    type_now = np.reshape(type_now, -1)
    index = id_map([type_now], ret_type(name_all))  # Pass a single-element list containing type_now to id_map
    return index

    
def unique_func(row, size=20):
    """
    return unique codes in row
    keep the order of codes
    """
    unique_elements = pd.unique(row)
    unique_elements = unique_elements[:size]
    return unique_elements


def now_time():
    """
    return time now
    """
    current_time = time.localtime()
    formatted_time = time.strftime("%Y-%m-%d %H:%M:%S", current_time)
    return formatted_time

start_time = now_time()


def save_hyperparameters(config, start_time):
    """
    save hyperparameters in config
    """
    with open(f"{config['path']}/output/{start_time}/hyper_par.csv", "a", newline="") as csvfile:
        fieldnames = list(config.keys())
        writer = csv.writer(csvfile)
        writer.writerow(fieldnames)
        writer.writerow(config.values())

        
def write_file_sub(MGB_AUC1, name):
    """
    write a AUC row in a file
    """
    column_names = "N"
    row_names = MGB_AUC1.index
    header = [None] * (len(row_names) * 2 + 2)
    header[2::2] = row_names
    header[3::2] = column_names * len(row_names)
    header[0] = "EPOCH"
    header[1] = "BATCH"
    with open(f"{config['path']}/output/{start_time}/{name}.csv", "a") as aucfile:
        aucwriter = csv.writer(aucfile)
        aucwriter.writerow(header)
        aucfile.close()

def write_file_sub2(MGB_AUC1, name, EPOCH, BATCH):
    """
    change the shape of a row so that it can bewritten into a file
    """
    reshaped_df = MGB_AUC1.T.unstack().to_frame().T
    reshaped_df.insert(0, "Batch", BATCH)
    reshaped_df.insert(0, "Epoch", EPOCH) 
    reshaped_df.to_csv(f"{config['path']}/output/{start_time}/{name}.csv", mode="a", index=False, header=False)



def write_file(Epoch, Batch, config, loss=None, pre=None, SIM_AUC=None, REL_AUC=None):
    """
    write all files (loss pre accuracy and AUC)
    """
    begin = not os.path.exists(f"{config['path']}/output/{start_time}")
    if begin:
        os.mkdir(f"{config['path']}/output/{start_time}") 
        # loss 
        lossfile =  open(f"{config['path']}/output/{start_time}/ALL_LOSS.csv", "a")
        losswriter = csv.writer(lossfile)
        if config['path_origin'] is None:
            losswriter.writerow(["EPOCH", "BATCH", "P_LOSS_hie", "N_LOSS_hie", "P_LOSS_OTOL", "N_LOSS_OTOL", 
                             "P_LOSS_LTOL", "N_LOSS_LTOL", "P_LOSS_SIM_NO_HIE", "N_LOSS_SIM_NO_HIE"])    
        else:
            losswriter.writerow(["EPOCH", "BATCH", "P_REL", "N_REL"])           
        lossfile.close()
        
        if config['path_origin'] is None:
            # auc
            write_file_sub(SIM_AUC, "SIM_AUC")
            # pre
            prefile = open(f"{config['path']}/output/{start_time}/ALL_PRE.csv", "a")
            prewriter = csv.writer(prefile)
            prewriter.writerow(["EPOCH", "BATCH", "TOP1", "TOP5", "TOP10", "TOP20"])
            prefile.close()
        else:
            # auc
            write_file_sub(REL_AUC, "REL_AUC")
            
        # tuning parameters
        save_hyperparameters(config, start_time)
        
    if loss is not None:
        lossfile = open(f"{config['path']}/output/{start_time}/ALL_LOSS.csv", "a", newline="")
        losswriter = csv.writer(lossfile)
        loss_row = [None] * (len(loss) + 2)
        loss_row[0] = Epoch
        loss_row[1] = Batch
        loss_row[2:] = loss
        losswriter.writerow(loss_row)  

    if pre is not None:
        prefile = open(f"{config['path']}/output/{start_time}/ALL_PRE.csv", "a")
        prewriter = csv.writer(prefile)
        pre_row = [None] * 6
        pre_row[0] = Epoch
        pre_row[1] = Batch
        pre_row[2:] = pre
        prewriter.writerow(pre_row)

    if REL_AUC is not None:
        write_file_sub2(REL_AUC, "REL_AUC", Epoch, Batch)
    if SIM_AUC is not None:
        write_file_sub2(SIM_AUC, "SIM_AUC", Epoch, Batch)
        

def mask_inst(pairs, dict_MGB, shift):
    
    mask = pairs["code1"].isin(dict_MGB) & pairs["code2"].isin(dict_MGB)
    pairs_MGB = pairs[mask]
    pairs_MGB.index = range(pairs_MGB.shape[0])
    temp = np.array(id_map(pairs_MGB["code1"], dict_MGB))
    temp2 = np.array(id_map(pairs_MGB["code2"], dict_MGB))
    pairs_MGB["Var1"] = temp + shift
    pairs_MGB["Var2"] = temp2 + shift
    return(pairs_MGB)

def split_train_set(unique_name, REL_pairs, scale=[0.5, 0.3], seed=42):
    # Set a seed for reproducibility
    random_state = seed
    
    # split train pairs
    num_rows = int(scale[0] * len(REL_pairs)) # add scale ratio of pairs into adj matrix (as train set)
    train_pairs = REL_pairs.sample(n=num_rows, random_state=random_state)
    remaining = REL_pairs[~REL_pairs.index.isin(train_pairs.index)]

    # Split remaining data into validation and test sets
    num_validation = int(scale[1] * len(REL_pairs))
    val_pairs = remaining.sample(n=num_validation, random_state=random_state)
    test_pairs = remaining[~remaining.index.isin(val_pairs.index)]
    
    return train_pairs, val_pairs, test_pairs


def retain_topk_alpha(alpha, edge_index, mask_num):
    """
    Retains the top-k alpha values for each source code in an adjacency list and masks the remaining values.

    Parameters:
    - alpha: Original alpha values for each edge.
    - edge_index: Original edge list.
    - mask_num: Value to mask non-top-k alpha values.
    - k (default: config["Truncate"]): Number of top alpha values to retain for each source code.

    Returns:
    - Updated alpha values with top-k retained and others masked.
    """

    # Find unique source nodes
    source_nodes = torch.unique(edge_index[0])
    
    # Mask to store which alphas to keep
    mask = torch.zeros_like(alpha, dtype=torch.bool)
    k = config["Truncate"]
    
    for source in source_nodes:
        # Find edges from the current source
        edge_indices = (edge_index[0] == source).nonzero(as_tuple=True)[0]
        # Adjust k if necessary
        actual_k = min(k, edge_indices.size(0))
        if actual_k > 0:  # This is to ensure that we don"t try to get top 0 values
            topk_indices = torch.topk(alpha[edge_indices].squeeze(1), k=actual_k, largest=True).indices
            mask[edge_indices[topk_indices]] = True
    
    # Set the values not in the top k to mask_num, like -100
    alpha[~mask] = mask_num
    return alpha


def get_parent(pairs, CHANGE_INDEX=[0, 1], DROP=True):

    pairs_new = pairs.copy()
    hie_all = pd.read_csv("https://han-attention.s3.amazonaws.com/input_new/Hierarchy/hie_rxn_phe_loi_0902.csv")
    to_remove = []  # list to store indices to be removed

    for col_idx in CHANGE_INDEX:

        # Fetch indices for which the pattern matches in the current column
        indices = grep_index("^LOINC:(?!LP)", np.array([str(item) if not pd.isna(item) else "nan" for item in pairs_new.iloc[:, col_idx].values]))

        for i in indices:
            mapped_values = hie_all.iloc[id_map([pairs_new.iloc[i, col_idx]], hie_all.iloc[:,0].values), 1].values

            if len(mapped_values) > 0:
                pairs_new.iloc[i, col_idx] = mapped_values[0]
            else:
                to_remove.append(i)
                
    pairs_new = pairs_new.reset_index(drop=True)
    if DROP:
        pairs_new.drop(to_remove, inplace=True)
        pairs_new = pairs_new.reset_index(drop=True)
    
        
    return pairs_new
    
    
    
def get_latent_related(train_pairs, val_pairs, test_pairs, DROP=True):
    
    train_pairs = get_parent(train_pairs, [0,1], DROP=DROP)
    val_pairs = get_parent(val_pairs, [0,1], DROP=DROP)
    test_pairs = get_parent(test_pairs, [0,1], DROP=DROP)
    
    return train_pairs, val_pairs, test_pairs


def get_index(train_rel_pairs, name_all):
    # Convert to set for faster membership checking
    code1_set = set(train_rel_pairs["code1"].tolist())
    code2_set = set(train_rel_pairs["code2"].tolist())

    # Ensure name_all is a list for proper membership checking
    if isinstance(name_all, pd.Series):
        name_all = name_all.tolist()
    elif isinstance(name_all, np.ndarray):
        name_all = name_all.tolist()
    # else assume it"s already a list

    rel_index_1 = np.where([name in code1_set for name in name_all])[0]
    rel_index_2 = np.where([name in code2_set for name in name_all])[0]
    rel_index = np.unique(np.union1d(rel_index_1, rel_index_2))

    return rel_index

def process_predictions(Pre, LEVEL, other_name, item, item_dict):
    n = len(Pre)
    right_top1 = np.zeros(n)
    right_top5 = np.zeros(n)
    right_top10 = np.zeros(n)
    right_top20 = np.zeros(n)
    ans = 0
    for i in range(n):
        predict_top1 = Pre[i, 0]
        predict_top5 = Pre[i, 0:5]
        predict_top10 = Pre[i, :10]
        predict_top20 = Pre[i, :]
        
        ans += 1
        level_key = "LEVEL" + str(LEVEL)
        level_data = item[list(item_dict.keys()).index(other_name[i])][1][level_key]

        right_top1[i] = int(predict_top1 in level_data)
        right_top5[i] = int(any(np.isin(predict_top5, level_data)))
        right_top10[i] = int(any(np.isin(predict_top10, level_data)))
        right_top20[i] = int(any(np.isin(predict_top20, level_data)))

    return right_top1, right_top5, right_top10, right_top20, ans

def solve_Procrustes(X1, X2):
    """
    \Omega = argmin ||X1 - X2\Omega||_F
    X1: local code
    X2: LOINC code sapbert emb

    In this function, we can get the best \Omega, so that we can get the new Loinc and the new TOP20
    """
    temp = X2.T @ X1
    u, s, vt = svd(temp)
    return u @ vt


def append_to_csv(name, row):
    if isinstance(row, tuple):
        for i, r in enumerate(row):
            file_name = f"{config['path']}/output/{start_time}/{name}_{i+1}.csv"
            r = r.squeeze().tolist() # convert tensor to list
            with open(file_name, "a", newline="") as f:
                writer = csv.writer(f)
                writer.writerow(r)
    else:
        file_name = f"{config['path']}/output/{start_time}/{name}.csv"
        row = row.squeeze().tolist() # convert tensor to list
        with open(file_name, "a", newline="") as f:
            writer = csv.writer(f)
            writer.writerow(row)
        
        
def my_item(x):
    if x is None:
        return None
    elif not isinstance(x, torch.Tensor):
         x = torch.tensor(x)
    return x.item()


def weight_auc(RELA_MGB_AUC):
    return sum(RELA_MGB_AUC[0].num.values[~np.isnan(RELA_MGB_AUC[0].auc.values)] * RELA_MGB_AUC[0].auc.values[~np.isnan(RELA_MGB_AUC[0].auc.values)])/sum(RELA_MGB_AUC[0].num.values[~np.isnan(RELA_MGB_AUC[0].auc.values)])


def func_type(RELA_MGB_AUC):
    return RELA_MGB_AUC[0].iloc[~np.isnan(RELA_MGB_AUC[0].auc.values),]


def sum_(SIMI_MGB):
    return(sum(func_type(SIMI_MGB).iloc[:,0].values *  func_type(SIMI_MGB).iloc[:,1].values)/sum(func_type(SIMI_MGB).iloc[:,1].values))



def my_diff(cos1, true_rank):
    ans = [np.mean(compute_spearman(cos1[i,:], true_rank)) for i in range(cos1.shape[0])]
    return ans



def combine_2_array(array1, array2):

    array1 = torch.tensor(array1)
    array2 = torch.tensor(array2)

    # Repeat each element of array1 len(array2) times
    array1_rep = array1.repeat_interleave(len(array2))

    # Repeat array2 len(array1) times
    array2_rep = array2.repeat(len(array1))

    # Combine the arrays
    combined = torch.stack((array1_rep, array2_rep), dim=1)
    return combined